name: biotables
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - jupyter
  - click
  - pandas
  - pip
  - pip:
      - pycomfort
      - gspread
      - polars
      - getpaper>=0.4.2
      - indexpaper>=0.0.15
      - langchain>=0.0.333
      - langserve>=0.0.29
      - sse_starlette
      - langchain-cli
      - uvicorn[standard]
      - git+https://github.com/antonkulaga/fastapi-cache.git
      - pdfminer
      - redis
